version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cripto
      POSTGRES_DB: proyecto_cripto
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  streamlit_app:
    build:
      context: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: proyecto_cripto
      DATABASE_USER: admin
      DATABASE_PASSWORD: cripto
    volumes:
      - .:/app

volumes:
  pgdata:
